version: 0.2

env:
  parameter-store:
    TABLE_NAME: TABLE_NAME
    REGION: REGION
    SQS_QUEUE_URL: SQS_QUEUE_URL
    AWS_ACCOUNT_ID: AWS_ACCOUNT_ID
  variables:
    SERVERLESS_ACCESS_KEY: ${SERVERLESS_ACCESS_KEY}

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - serverless deploy --stage dev

artifacts:
  files:
    - "**/*"
